<?php
/**
 * @package    tpl_itheme
 * @author     Pavel Lange <pavel@ilange.ru>
 * @link       https://github.com/i-lange/tpl_itheme
 * @copyright  (C) 2026 Pavel Lange <https://ilange.ru>
 * @license    GNU General Public License version 2 or later
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\Helper\ModuleHelper;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Associations;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\FileLayout;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Content\Site\Helper\RouteHelper;

/** @var \Joomla\Component\Content\Site\View\Article\HtmlView $this */
// Create shortcuts to some parameters.
$params  = $this->item->params;
$canEdit = $params->get('access-edit');
$user    = $this->getCurrentUser();
$info    = $params->get('info_block_position', 0);

// Check if associations are implemented. If they are, define the parameter.
$assocParam        = (Associations::isEnabled() && $params->get('show_associations'));
$currentDate       = Factory::getDate()->format('Y-m-d H:i:s');
$isNotPublishedYet = $this->item->publish_up > $currentDate;
$isExpired         = !is_null($this->item->publish_down) && $this->item->publish_down < $currentDate;

$doc = Factory::getApplication()->getDocument();
$rend = $doc->loadRenderer('module');
$sidebar = (isset(ModuleHelper::getModules('sidebar-news')[0])) ? ModuleHelper::getModules('sidebar-news')[0] : false;

$template = Factory::getApplication()->getTemplate(true)->params;
?>
<div class="row gy-4 gx-5">
<article class="col-12 <?php echo ($sidebar) ? 'col-md-7 col-lg-8 ' : ''; ?><?php echo $this->pageclass_sfx; ?>">
    <meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? Factory::getApplication()->get('language') : $this->item->language; ?>">
    <?php if (!empty($this->item->pagination) && !$this->item->paginationposition && $this->item->paginationrelative) {
        echo $this->item->pagination;
    } ?>

    <?php $useDefList = $params->get('show_modify_date') || $params->get('show_publish_date') || $params->get('show_create_date')
    || $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam; ?>

    <?php if ($params->get('access-view')) : ?>
        <?php echo LayoutHelper::render('joomla.content.full_image', $this->item); ?>
    <?php endif; ?>

    <?php if ($params->get('show_title')) : ?>
        <h1><?php echo $this->escape($this->item->title); ?></h1>
    <?php endif; ?>

    <?php if ($useDefList && ($info == 0 || $info == 2)) : ?>
        <?php echo LayoutHelper::render('joomla.content.info_block', ['item' => $this->item, 'params' => $params, 'position' => 'above']); ?>
    <?php endif; ?>

    <?php if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
        <?php $this->item->tagLayout = new FileLayout('joomla.content.tags'); ?>

        <?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
    <?php endif; ?>

    <?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
    <?php echo $this->item->event->beforeDisplayContent; ?>

    <?php if ((int) $params->get('urls_position', 0) === 0) : ?>
        <?php echo $this->loadTemplate('links'); ?>
    <?php endif; ?>
    <?php if ($params->get('access-view')) : ?>
        <?php
        if (!empty($this->item->pagination) && !$this->item->paginationposition && !$this->item->paginationrelative) :
            echo $this->item->pagination;
        endif;
        ?>
        <?php if (isset($this->item->toc)) :
            echo $this->item->toc;
        endif; ?>

        <?php echo $this->item->text; ?>

        <section class="card card-rounded border-0 bg-light my-4" aria-labelledby="contacts-platforms-title">
            <div class="card-body p-4">
                <h2 class="h5 mb-3" id="contacts-platforms-title">Мессенджеры и другие платформы</h2>
                <div class="row row-cols-2 row-cols-lg-4 g-2">
                    <?php if ($url = $template->get('siteTelegram', false)) : ?>
                        <div class="col">
                            <a class="btn btn-telegram w-100"
                               href="<?php echo $url; ?>"
                               target="_blank"
                               title="<?php echo Text::_('TPL_ITHEME_CONTACTS_TELEGRAM_LABEL'); ?>"
                               aria-label="<?php echo Text::_('TPL_ITHEME_CONTACTS_TELEGRAM_LABEL'); ?>"
                               rel="noopener noreferrer">
                                <?php echo LayoutHelper::render('itheme.icon', ['icon' => 'i-telegram']); ?>
                                <span><?php echo Text::_('TPL_ITHEME_CONTACTS_TELEGRAM_LABEL'); ?></span></a>
                        </div>
                    <?php endif; ?>
                    <?php if ($url = $template->get('siteViber', false)) : ?>
                        <div class="col">
                            <a class="btn btn-viber w-100"
                               href="<?php echo $url; ?>"
                               target="_blank"
                               title="<?php echo Text::_('TPL_ITHEME_CONTACTS_VIBER_LABEL'); ?>"
                               aria-label="<?php echo Text::_('TPL_ITHEME_CONTACTS_VIBER_LABEL'); ?>"
                               rel="noopener noreferrer">
                                <?php echo LayoutHelper::render('itheme.icon', ['icon' => 'i-viber']); ?>
                                <span><?php echo Text::_('TPL_ITHEME_CONTACTS_VIBER_LABEL'); ?></span></a>
                        </div>
                    <?php endif; ?>
                    <?php if ($url = $template->get('siteYouTube', false)) : ?>
                        <div class="col">
                            <a class="btn btn-youtube w-100"
                               href="<?php echo $url; ?>"
                               target="_blank"
                               title="<?php echo Text::_('TPL_ITHEME_CONTACTS_YOUTUBE_LABEL'); ?>"
                               aria-label="<?php echo Text::_('TPL_ITHEME_CONTACTS_YOUTUBE_LABEL'); ?>"
                               rel="noopener noreferrer"><?php echo LayoutHelper::render('itheme.icon', ['icon' => 'i-youtube']); ?>
                                <span><?php echo Text::_('TPL_ITHEME_CONTACTS_YOUTUBE_LABEL'); ?></span></a>
                        </div>
                    <?php endif; ?>
                    <?php if ($url = $template->get('siteWildberries', false)) : ?>
                        <div class="col">
                            <a class="btn btn-wildberries w-100"
                               href="<?php echo $url; ?>"
                               target="_blank"
                               title="<?php echo Text::_('TPL_ITHEME_CONTACTS_WILDBERRIES_LABEL'); ?>"
                               aria-label="<?php echo Text::_('TPL_ITHEME_CONTACTS_WILDBERRIES_LABEL'); ?>"
                               rel="noopener noreferrer">
                                <span><?php echo Text::_('TPL_ITHEME_CONTACTS_WILDBERRIES_LABEL'); ?></span>
                            </a>
                        </div>
                    <?php endif; ?>
                    <?php if ($url = $template->get('siteOzon', false)) : ?>
                        <div class="col">
                            <a class="btn btn-ozon w-100"
                               href="<?php echo $url; ?>"
                               target="_blank"
                               title="<?php echo Text::_('TPL_ITHEME_CONTACTS_OZON_LABEL'); ?>"
                               aria-label="<?php echo Text::_('TPL_ITHEME_CONTACTS_OZON_LABEL'); ?>"
                               rel="noopener noreferrer">
                                <span><?php echo Text::_('TPL_ITHEME_CONTACTS_OZON_LABEL'); ?></span>
                            </a>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </section>

        <section class="card card-rounded my-4" aria-labelledby="contacts-details-title">
            <div class="card-body p-4">
                <h2 class="h5 mb-3" id="contacts-details-title">Реквизиты компании</h2>
                <div class="table-responsive">
                    <table class="table table-borderless align-middle mb-0">
                        <tbody>
                        <?php if ($template->get('siteLegal', false)) : ?>
                            <tr class="border-bottom">
                                <th class="text-body-secondary fw-normal ps-0 w-50" scope="row">Полное наименование</th>
                                <td class="pe-0"><?php echo Text::_('TPL_ITHEME_CONTACTS_LEGAL_LABEL'); ?></td>
                            </tr>
                        <?php endif; ?>
                        <?php if ($value = $template->get('siteUnp', false)) : ?>
                            <tr class="border-bottom">
                                <th class="text-body-secondary fw-normal ps-0" scope="row">УНП</th>
                                <td class="pe-0"><?php echo $value; ?></td>
                            </tr>
                        <?php endif; ?>
                        <?php if ($value = $template->get('siteAccount', false)) : ?>
                            <tr class="border-bottom">
                                <th class="text-body-secondary fw-normal ps-0" scope="row"><?php echo Text::_('TPL_ITHEME_CONTACTS_ACCOUNT_LABEL'); ?></th>
                                <td class="pe-0"><?php echo $value; ?></td>
                            </tr>
                        <?php endif; ?>
                        <?php if ($template->get('siteAddress', false)) : ?>
                            <tr class="border-bottom">
                                <th class="text-body-secondary fw-normal ps-0" scope="row">Юридический адрес</th>
                                <td class="pe-0"><?php echo Text::_('TPL_ITHEME_CONTACTS_ADDRESS_LABEL'); ?></td>
                            </tr>
                        <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </section>

        <?php if ($info == 1 || $info == 2) : ?>
            <hr>
            <?php if ($useDefList) : ?>
                <?php echo LayoutHelper::render('joomla.content.info_block', ['item' => $this->item, 'params' => $params, 'position' => 'below']); ?>
            <?php endif; ?>
            <?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
                <?php $this->item->tagLayout = new FileLayout('joomla.content.tags'); ?>
                <?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
            <?php endif; ?>
        <?php endif; ?>

        <?php
        if (!empty($this->item->pagination) && $this->item->paginationposition && !$this->item->paginationrelative) :
            echo $this->item->pagination;
            ?>
        <?php endif; ?>
        <?php if ((int) $params->get('urls_position', 0) === 1) : ?>
            <?php echo $this->loadTemplate('links'); ?>
        <?php endif; ?>
        <?php // Optional teaser intro text for guests ?>
    <?php elseif ($params->get('show_noauth') && $user->guest) : ?>
        <?php echo LayoutHelper::render('joomla.content.intro_image', $this->item); ?>
        <?php echo HTMLHelper::_('content.prepare', $this->item->introtext); ?>
        <?php // Optional link to let them register to see the whole article. ?>
        <?php if ($params->get('show_readmore') && $this->item->fulltext != null) : ?>
            <?php $menu = Factory::getApplication()->getMenu(); ?>
            <?php $active = $menu->getActive(); ?>
            <?php $itemId = $active->id; ?>
            <?php $link = new Uri(Route::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false)); ?>
            <?php $link->setVar('return', base64_encode(RouteHelper::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language))); ?>
            <?php echo LayoutHelper::render('joomla.content.readmore', ['item' => $this->item, 'params' => $params, 'link' => $link]); ?>
        <?php endif; ?>
    <?php endif; ?>
    <?php
    if (!empty($this->item->pagination) && $this->item->paginationposition && $this->item->paginationrelative) :
        echo $this->item->pagination;
        ?>
    <?php endif; ?>
    <?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
    <?php echo $this->item->event->afterDisplayContent; ?>
</article>
<?php if ($sidebar) : ?>
    <div class="col-12 col-md-5 col-lg-4"><?php echo $rend->render($sidebar, ['style' => 'none']); ?></div>
<?php endif; ?>
</div>
